baseurl: "http://localhost:1313/"
title: "ISMIS 2022"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "ISMIS 2022"
  Description: "The 26th International Symposium on Methodologies for Intelligent Systems"
  Date: "3rd-5th October 2022"
  # Price: "" # If your event is free, just comment this line
  Venue: "UNICAL - Università della Calabria"
  Address: "Via Pietro Bucci, 12"
  City:  "Cosenza"
  State: "Italy"
  Images: ["/img/cover.jpg"]
  # GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - cfp
    - industry
    - sponsors
    - venue
    - committees
    - schedule
    - bp

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    cfp: "Call for Papers"
    industry: "Industry Session"
    sponsors: "Sponsors"
    venue: "Venue"
    committees: "Committees"
    schedule: "Schedule"
    bp: "Best Papers"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  # CallToAction:
  #   text: "Register now!"
  #   link: "http://register.example.com"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  # ForkButton:
  #   repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "ICAR-CNR"
      logo: "/img/logo_icar.jpg"
      url: "https://www.icar.cnr.it"

  # List of Partners
  # Partners:
  #   - name: "Hugo"
  #     logo: "/img/hugo.jpg"
  #     url: "https://gohugo.io"
  #   - name: "BrazilJS"
  #     logo: "/img/partner.png"
  #     url: "http://braziljs.org"

  # The entire schedule
  Schedule:
    - name: "To be defined"
      time: "0h00"
